apiVersion: v1
kind: Service
metadata:
  name: visualizer
  namespace: offline-search
spec:
  type: NodePort
  selector:
    app: visualizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
